services:
  - type: web
    name: daily-tv-serials
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PYTHONPATH
        value: .